#!/bin/bash

# 定义实际执行的脚本路径
REAL_SCRIPT="/var/packages/${SYNOPKG_PKGNAME}/scripts/real-start-stop-status"

# 使用 spm-exe 提权执行 real-start-stop-status 脚本，并传递所有参数
/usr/local/bin/spm-exec $REAL_SCRIPT $@

# 获取执行结果，并退出
exit $?
